import '@fontsource/marcellus/400.css'
import '@fontsource/cormorant/500-italic.css'
import '@fontsource/instrument-sans/400.css'
import '@fontsource/instrument-sans/500.css'
import '@fontsource/instrument-sans/400-italic.css'
import '@fontsource/spline-sans-mono/300.css'
import '@fontsource/spline-sans-mono/400.css'

import './base.css'
import './code.css'
import './layouts.css'
