name: Deploy to DigitalOcean
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Trigger Deployment
        shell: bash
        run: |
          DEPLOY_ID=$(doctl apps create-deployment ${{ secrets.APP_UUID }} --force-rebuild -o json | jq -r '.[0].id')
          echo "Deployment started with ID: $DEPLOY_ID"
          LASTPHASE=""
          while true
          do
            PHASE=$(doctl apps get-deployment ${{ secrets.APP_UUID }} $DEPLOY_ID -o json | jq -r '.[0].phase')
            if [[ $PHASE = "ACTIVE" ]]
            then
              echo "Deployment complete!"
              break
            fi
            if [[ $PHASE = "ERROR" ]]
            then
              echo "Deployment failed!"
              exit 1
            fi
            if [[ $PHASE != $LASTPHASE ]]
            then
              echo "Deployment phase: $PHASE"
              LASTPHASE=$PHASE
            fi
            sleep 3 
          done
